data:
  dataset:
    name: domainnet # choices are ['office', 'officehome', 'caltech-imagenet', 'visda2017']
    root_path: ../data/domainnet # /path/to/dataset/root
    source: 2 # source domain index
    target: 4 # target domain index
    n_share: 150 # number of classes to be shared
    n_source_private: 50 # number of classes in source private domain
    n_total: 345 # number of classes in total

  dataloader:
    class_balance: true #
    data_workers: 3 # how many workers to use for train dataloaders
    batch_size: 36 # batch_size for source domain and target domain respectively

model:
  base_model: resnext101 # choices=['resnet50', 'resnext101']
  pretrained_model: ./pretrained/resnext101.pth # /path/to/pretrained/model

train:
  min_step: 20000 # minimum steps to run. run epochs until it exceeds the minStep
  lr: 0.01 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  weight_decay: 0.0005
  momentum: 0.9

test:
  test_interval: 500 # interval of two continuous test phase
  test_only: True # test a given model and exit
  resume_file: current.pkl # model to test
  w_0: 0.55 # hyper-parameter w_0

misc:
  gpus: 1 # how many GPUs to be used, 0 indicates CPU only

log:
  root_dir: log/domainnet_test/time/ # the log directory (log directory will be {root_dir}/{method}/time/)
  log_interval: 10 # steps to log scalars